---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pip-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/shgovind/Downloads  # Use the same path as in your kind config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pip-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
