apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: app-pr
spec:
  pipelineRef:
    name: app-pl
  params:
    - name: git-url
      value: "https://github.com/codequester/sample-java-gradle-app.git"
    - name: branch
      value: "main"   
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: pip-pvc
  serviceAccountName: tekton-sa  # Add service account if necessary
  #secrets:
  #  - secretName: docker-secret