apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: app-pr
spec:
  pipelineRef:
    name: app-pl
  params:
    - name: release-name
      value: "sample-java-gradle-app"  # Set your Helm release name    
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: pip-pvc
  serviceAccountName: tekton-sa  # Add service account if necessary
  #secrets:
  #  - secretName: docker-secret